export { default as Header } from './Header/Header.jsx';
export { default as CourseForm } from './CourseForm/CourseForm.jsx';
export { default as Courses } from './Courses/Courses.jsx';
export { default as Registration } from './Registration/Registration.jsx';
export { default as CourseInfo } from './CourseInfo/CourseInfo.jsx';
export { default as Login } from './Login/Login.jsx';
export { default as Container } from './Container/Container.jsx';
export { default as ProtectedRoute } from './ProtectedRoute/ProtectedRoute.jsx';
export { default as PrivateRouter } from './PrivateRouter/PrivateRouter.jsx';
